name: Deploy Python project to Azure Function App

# only run for ingest function app code changes 
on:
  push:
    branches:
    - main
    paths:
    - 'ingest/queue-trigger-py/src/purple-ingest/**'

# CONFIGURATION
# Create the empty Azure Function App FIRST 
#
# For help, go to https://github.com/Azure/Actions
#
# 1. Set up the following secrets in your repository:
#   AZURE_FUNCTIONAPP_PUBLISH_PROFILE
#
# 2. Change these variables for your configuration:
env:
  PURPLE_FUNCTIONAPP_NAME: 'PurpleQTrggrFunc001' 
  PURPLE_PACKAGE_PATH: 'ingest/queue-trigger-py/src/purple-ingest/' 
  PYTHON_VERSION: '3.11' 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4
      with:
        ref: main
        sparse-checkout: ${{ env.PURPLE_PACKAGE_PATH }}
        sparse-checkout-cone-mode: false

    - name: 'Display directory content'
      shell: bash
      run: |
        pwd
        ls -l
        cd ${{ env.PURPLE_PACKAGE_PATH }}
        pwd
        ls -l

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: 'Resolve Project Dependencies Using Pip'
      shell: bash
      run: |
        pushd './${{ env.PURPLE_PACKAGE_PATH }}'
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.PURPLE_FUNCTIONAPP_NAME }}
        package: ${{ env.PURPLE_PACKAGE_PATH }}
        publish-profile: ${{ secrets.PURPLE_PUBLISH_PROFILE }}
        scm-do-build-during-deployment: true
        enable-oryx-build: true

# For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples